[project]
name = "picoctf-archive"
version = "0.1.0"
description = "My picoCTF archive"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pwntools>=4.14.0",
]

[tool.ruff]
# allow star imports for pwntools
ignore = [
    "F403",
    "F405"
]
